---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
  labels:
    app: hotstar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: pavan73384/hotstar:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: hotstar-service
spec:
  type: LoadBalancer
  selector:
    app: hotstar
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

    